Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 99
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false