version: '3'
services:
  db:
    image: postgres
    #restart: always
    volumes:
      - /data/pgsql:/var/lib/pgsql
    env_file: .env
    ports:
        - 5432:5432
  mailcatcher:
    image: yappabe/mailcatcher
    #restart: always
    ports:
        - 1025:1025
        - 1080:1080